
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ABIR
 */
public class create_Voucher extends javax.swing.JFrame {
    int name,exp_id,v_id;
    
    private  Statement stmt = null;
    private static Connection connection ;
    /**
     * Creates new form create_Voucher
     */
    public create_Voucher() {
        initComponents();
    }
     public create_Voucher(int username) throws ClassNotFoundException, SQLException {
         System.out.println("Hello from create page");
        initComponents();
        name=username;
        System.out.println("DB connection Starting..create voucher page");
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost:1433;"
                + "user=sa;password=p@ssword13;" 
                + "databaseName=voucher;";
        connection = DriverManager.getConnection(connectionUrl);
        System.out.println("Connected database successfully.........");
         stmt = connection.createStatement();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loweLabel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        vc_hub_btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description_label = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        amount_label = new javax.swing.JTextField();
        submit_button = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        e_s_name_combobox = new javax.swing.JComboBox<>();
        expense_type_id_label = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        exp_sec_combo = new javax.swing.JComboBox<>();
        exp_sec_label = new javax.swing.JTextField();
        exp_sec_id = new javax.swing.JLabel();
        voucher_id_label = new javax.swing.JLabel();
        voucher_details_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(681, 600));
        setMinimumSize(new java.awt.Dimension(681, 600));
        setPreferredSize(new java.awt.Dimension(681, 600));
        getContentPane().setLayout(null);

        loweLabel.setBackground(new java.awt.Color(255, 255, 255));
        loweLabel.setMaximumSize(new java.awt.Dimension(681, 751));
        loweLabel.setMinimumSize(new java.awt.Dimension(681, 751));
        loweLabel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(24, 44, 97));

        vc_hub_btn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        vc_hub_btn.setForeground(new java.awt.Color(255, 255, 255));
        vc_hub_btn.setText("Create Voucher");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gift-vou.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vc_hub_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(vc_hub_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        loweLabel.add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 116);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Voucher ID:");
        loweLabel.add(jLabel2);
        jLabel2.setBounds(370, 150, 80, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Expense Type Name:");
        loweLabel.add(jLabel3);
        jLabel3.setBounds(30, 140, 130, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Description:");
        loweLabel.add(jLabel4);
        jLabel4.setBounds(30, 350, 89, 22);

        description_label.setColumns(20);
        description_label.setRows(5);
        jScrollPane1.setViewportView(description_label);

        loweLabel.add(jScrollPane1);
        jScrollPane1.setBounds(120, 360, 190, 130);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Issue Date:");
        loweLabel.add(jLabel5);
        jLabel5.setBounds(370, 200, 70, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Amount:");
        loweLabel.add(jLabel6);
        jLabel6.setBounds(380, 340, 60, 20);

        amount_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_labelActionPerformed(evt);
            }
        });
        loweLabel.add(amount_label);
        amount_label.setBounds(470, 330, 120, 30);

        submit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SubmitApplication.png"))); // NOI18N
        submit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit_buttonMouseClicked(evt);
            }
        });
        loweLabel.add(submit_button);
        submit_button.setBounds(280, 500, 140, 50);
        loweLabel.add(jDateChooser1);
        jDateChooser1.setBounds(370, 250, 250, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Expense Type ID:");
        loweLabel.add(jLabel8);
        jLabel8.setBounds(30, 180, 115, 22);

        e_s_name_combobox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        e_s_name_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debit", "Credit" }));
        e_s_name_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_s_name_comboboxActionPerformed(evt);
            }
        });
        loweLabel.add(e_s_name_combobox);
        e_s_name_combobox.setBounds(160, 140, 140, 26);

        expense_type_id_label.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        loweLabel.add(expense_type_id_label);
        expense_type_id_label.setBounds(160, 180, 100, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Expense Sector ID:");
        loweLabel.add(jLabel9);
        jLabel9.setBounds(30, 300, 140, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Expense Sector Name:");
        loweLabel.add(jLabel10);
        jLabel10.setBounds(30, 220, 140, 30);

        exp_sec_combo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exp_sec_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Gift", "Transport", "Electricity", "Others" }));
        exp_sec_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exp_sec_comboActionPerformed(evt);
            }
        });
        loweLabel.add(exp_sec_combo);
        exp_sec_combo.setBounds(30, 260, 150, 30);

        exp_sec_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exp_sec_labelMousePressed(evt);
            }
        });
        loweLabel.add(exp_sec_label);
        exp_sec_label.setBounds(200, 260, 120, 30);

        exp_sec_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loweLabel.add(exp_sec_id);
        exp_sec_id.setBounds(150, 300, 110, 30);

        voucher_id_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loweLabel.add(voucher_id_label);
        voucher_id_label.setBounds(450, 144, 110, 30);

        voucher_details_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voucher_details.png"))); // NOI18N
        voucher_details_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voucher_details_btnMouseClicked(evt);
            }
        });
        loweLabel.add(voucher_details_btn);
        voucher_details_btn.setBounds(440, 490, 210, 50);

        getContentPane().add(loweLabel);
        loweLabel.setBounds(0, 0, 680, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void amount_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_labelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_labelActionPerformed

    private void submit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_buttonMouseClicked
        String expense_type_name = e_s_name_combobox.getSelectedItem().toString();
        int expense_typeid = Integer.parseInt(expense_type_id_label.getText());
        String expense_sector_name="";
        if (expense_typeid==1)
        {
            expense_sector_name = exp_sec_combo.getSelectedItem().toString();
        }
        else
        {
            expense_sector_name = exp_sec_label.getText();
        }
        int exp_sectorid = Integer.parseInt(exp_sec_id.getText());
        String descr = description_label.getText();
        int vid = Integer.parseInt(voucher_id_label.getText());
        java.util.Date date=jDateChooser1.getDate();
        java.sql.Date sDate = new java.sql.Date(date.getTime()); 
        int amn= Integer.parseInt(amount_label.getText());
        String insertQuery_voucher = "INSERT INTO voucher (voucher_id, expense_type_id,user_id)\n" +    
                               "VALUES (?,?,?)";
        
        PreparedStatement queryStatement_voucher;
        try {
            queryStatement_voucher = connection.prepareStatement(insertQuery_voucher);
            queryStatement_voucher.setInt(1, vid);
            queryStatement_voucher.setInt(2, expense_typeid);
            queryStatement_voucher.setInt(3, name);
            
            int rowCount_voucher = queryStatement_voucher.executeUpdate();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(create_Voucher.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        String insertQuery_voucher_details = "INSERT INTO voucher_details (voucher_id,expense_sector_id,description,issue_date,amount)\n" +    
                               "VALUES (?,?,?,?,?)";
        
        PreparedStatement queryStatement_voucher_details;
        try {
            queryStatement_voucher_details = connection.prepareStatement(insertQuery_voucher_details);
            queryStatement_voucher_details.setInt(1, vid);
            queryStatement_voucher_details.setInt(2, exp_sectorid);
            queryStatement_voucher_details.setString(3, descr);
            queryStatement_voucher_details.setDate(4, sDate);
            queryStatement_voucher_details.setInt(5, amn);
            int rowCount_voucher = queryStatement_voucher_details.executeUpdate();
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(create_Voucher.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        JFrame f=new JFrame();  
        JOptionPane.showMessageDialog(f,"Voucher Successfully Added");
        expense_type_id_label.setText("");
        exp_sec_id.setText("");
        description_label.setText("");
        voucher_id_label.setText("");
        amount_label.setText("");
        
        /*
         String vid = voucher_id_label.getText();
        String es_id = expense_sector_label.getText();
        String desp= description_label.getText();
        int amn= Integer.parseInt(amount_label.getText());
        java.util.Date date=jDateChooser1.getDate();
        java.sql.Date sDate = new java.sql.Date(date.getTime()); 
//        System.out.println(vid);
//        System.out.println(es_id);
//        System.out.println(desp);
//        System.out.println(amn);
//        System.out.println(sDate);
        
         String insertQuery = "INSERT INTO voucher_detail (voucher_id, expense_sector_id,description,issue_date,account)\n" +    
                               "VALUES (?,?,?,?,?)";
        
        PreparedStatement queryStatement;
        try {
            queryStatement = connection.prepareStatement(insertQuery);
            queryStatement.setString(1, vid);
            queryStatement.setString(2, es_id);
            queryStatement.setString(3, desp);
            queryStatement.setDate(4, sDate);
            queryStatement.setInt(5, amn);
            int rowCount = queryStatement.executeUpdate();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(create_Voucher.class.getName()).log(Level.SEVERE, null, ex);
        }

        */

        
    }//GEN-LAST:event_submit_buttonMouseClicked

    private void exp_sec_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp_sec_comboActionPerformed
         
        String exp_sec_combo_sel=exp_sec_combo.getSelectedItem().toString();
        if (exp_sec_combo_sel.equals("Food"))
        {
            exp_sec_id.setText("1");
        }
        else if (exp_sec_combo_sel.equals("Gift"))
        {
            exp_sec_id.setText("2");
        }
        else if (exp_sec_combo_sel.equals("Transport"))
        {
            exp_sec_id.setText("3");
        }
        else if (exp_sec_combo_sel.equals("Electricity"))
        {
            exp_sec_id.setText("4");
        }
        else if (exp_sec_combo_sel.equals("Others"))
        {
            exp_sec_id.setText("5");
        }
    }//GEN-LAST:event_exp_sec_comboActionPerformed

    private void e_s_name_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_s_name_comboboxActionPerformed
        String combo_name = e_s_name_combobox.getSelectedItem().toString();
        if (combo_name.equals("Debit"))
        {
            expense_type_id_label.setText("1");
            exp_id=1;
        }
        else
        {
            expense_type_id_label.setText("2");
            exp_id=2;
        }
        if (exp_id==1)
        {
             exp_sec_label.setEnabled(false);
             exp_sec_combo.setEnabled(true);
             
             String query = "SELECT COUNT(*) FROM [voucher].[dbo].[voucher] where expense_type_id=1";
            try {
                ResultSet rs = stmt.executeQuery(query);
                rs.next();
                v_id=rs.getInt(1)+100+1;
                voucher_id_label.setText(String.valueOf(v_id));
            } catch (SQLException ex) {
                Logger.getLogger(create_Voucher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            exp_sec_combo.setEnabled(false);
            exp_sec_label.setEnabled(true);
            
            String query = "SELECT COUNT(*) FROM [voucher].[dbo].[voucher] where expense_type_id=2";
            try {
                ResultSet rs = stmt.executeQuery(query);
                rs.next();
                v_id=rs.getInt(1)+200+1;
                voucher_id_label.setText(String.valueOf(v_id));
            } catch (SQLException ex) {
                Logger.getLogger(create_Voucher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_e_s_name_comboboxActionPerformed

    private void exp_sec_labelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exp_sec_labelMousePressed
        exp_sec_id.setText("6");
    }//GEN-LAST:event_exp_sec_labelMousePressed

    private void voucher_details_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voucher_details_btnMouseClicked

        try {
            voucher_display vou_dis = new voucher_display(name);
            this.setVisible(false);
            vou_dis.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(create_Voucher.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(create_Voucher.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_voucher_details_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_Voucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_label;
    private javax.swing.JTextArea description_label;
    private javax.swing.JComboBox<String> e_s_name_combobox;
    private javax.swing.JComboBox<String> exp_sec_combo;
    private javax.swing.JLabel exp_sec_id;
    private javax.swing.JTextField exp_sec_label;
    private javax.swing.JLabel expense_type_id_label;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel loweLabel;
    private javax.swing.JLabel submit_button;
    private javax.swing.JLabel vc_hub_btn;
    private javax.swing.JLabel voucher_details_btn;
    private javax.swing.JLabel voucher_id_label;
    // End of variables declaration//GEN-END:variables
}
