
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class search_by_voucher_id extends javax.swing.JFrame {
    int name;
    
    private  Statement stmt = null;
    private static Connection connection ;
    /**
     * Creates new form search_by_voucher_id
     */
    public search_by_voucher_id() {
        initComponents();
    }
    
    public search_by_voucher_id(int username) throws ClassNotFoundException, SQLException {
        initComponents();
        name=username;
        
        
        System.out.println("DB connection Starting..create voucher page");
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost:1433;"
                + "user=sa;password=p@ssword13;" 
                + "databaseName=voucher;";
        connection = DriverManager.getConnection(connectionUrl);
        System.out.println("Connected database successfully.........");
         stmt = connection.createStatement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_to_print = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        voucher_id_label = new javax.swing.JTextField();
        search_btn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        expense_sector_id_label = new javax.swing.JLabel();
        description_label = new javax.swing.JLabel();
        issue_date_label = new javax.swing.JLabel();
        amount_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        user_name_label = new javax.swing.JLabel();
        user_id_label = new javax.swing.JLabel();
        upperPanel = new javax.swing.JPanel();
        vc_hub_btn = new javax.swing.JLabel();
        show_name_Label = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        print_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(562, 468));
        setMinimumSize(new java.awt.Dimension(562, 468));
        setPreferredSize(new java.awt.Dimension(562, 468));
        getContentPane().setLayout(null);

        panel_to_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_to_print.setMinimumSize(new java.awt.Dimension(562, 468));
        panel_to_print.setPreferredSize(new java.awt.Dimension(562, 468));
        panel_to_print.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Voucher ID:");
        panel_to_print.add(jLabel1);
        jLabel1.setBounds(30, 19, 80, 30);

        voucher_id_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panel_to_print.add(voucher_id_label);
        voucher_id_label.setBounds(120, 20, 140, 30);

        search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        search_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_btnMouseClicked(evt);
            }
        });
        panel_to_print.add(search_btn);
        search_btn.setBounds(300, 20, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Expense Sector ID:");
        panel_to_print.add(jLabel3);
        jLabel3.setBounds(30, 80, 110, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Description: ");
        panel_to_print.add(jLabel4);
        jLabel4.setBounds(30, 220, 90, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Issue Date : ");
        panel_to_print.add(jLabel5);
        jLabel5.setBounds(30, 130, 90, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Amount: ");
        panel_to_print.add(jLabel6);
        jLabel6.setBounds(30, 180, 60, 20);

        expense_sector_id_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panel_to_print.add(expense_sector_id_label);
        expense_sector_id_label.setBounds(150, 80, 130, 20);

        description_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panel_to_print.add(description_label);
        description_label.setBounds(150, 220, 400, 30);

        issue_date_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panel_to_print.add(issue_date_label);
        issue_date_label.setBounds(150, 130, 140, 20);

        amount_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panel_to_print.add(amount_label);
        amount_label.setBounds(150, 180, 140, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Issued By");
        panel_to_print.add(jLabel2);
        jLabel2.setBounds(310, 70, 90, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("User Name:");
        panel_to_print.add(jLabel7);
        jLabel7.setBounds(310, 120, 80, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("User ID:");
        panel_to_print.add(jLabel8);
        jLabel8.setBounds(310, 160, 70, 20);

        user_name_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panel_to_print.add(user_name_label);
        user_name_label.setBounds(390, 114, 170, 30);

        user_id_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panel_to_print.add(user_id_label);
        user_id_label.setBounds(380, 150, 180, 40);

        getContentPane().add(panel_to_print);
        panel_to_print.setBounds(0, 90, 570, 280);

        upperPanel.setBackground(new java.awt.Color(24, 44, 97));
        upperPanel.setLayout(null);

        vc_hub_btn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        vc_hub_btn.setForeground(new java.awt.Color(255, 255, 255));
        vc_hub_btn.setText("Search By Voucher ID");
        upperPanel.add(vc_hub_btn);
        vc_hub_btn.setBounds(31, 31, 320, 38);

        show_name_Label.setBackground(new java.awt.Color(255, 255, 255));
        show_name_Label.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        show_name_Label.setForeground(new java.awt.Color(255, 255, 255));
        upperPanel.add(show_name_Label);
        show_name_Label.setBounds(630, 20, 110, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go_back_btn.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        upperPanel.add(jLabel9);
        jLabel9.setBounds(440, 20, 90, 50);

        getContentPane().add(upperPanel);
        upperPanel.setBounds(0, 0, 570, 90);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(562, 468));
        jPanel2.setPreferredSize(new java.awt.Dimension(562, 468));

        print_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print_button.png"))); // NOI18N
        print_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 370, 570, 100);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void search_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_btnMouseClicked
        int vid = Integer.parseInt(voucher_id_label.getText());
        String query = String.format("Select * from [voucher].[dbo].[voucher_details] where voucher_id=%d",vid);
        try {
            ResultSet rs = stmt.executeQuery(query);
            rs.next();
            int exp_sec_id=rs.getInt(2);
            String desp=rs.getString(3);
            
            java.sql.Date sDate=rs.getDate(4);
            java.util.Date utilDate = new java.util.Date(sDate.getTime());
            SimpleDateFormat sdf1 = new SimpleDateFormat("MMM dd,yyyy");
            System.out.println(sdf1);
            String DOB_String = sdf1.format(utilDate);
            int amn=rs.getInt(5);
            
            expense_sector_id_label.setText(Integer.toString(exp_sec_id));
            description_label.setText(desp);
            issue_date_label.setText(DOB_String);
            amount_label.setText(Integer.toString(amn));
            
        } catch (SQLException ex) {
            Logger.getLogger(search_by_voucher_id.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        String query2 = String.format("Select * from [voucher].[dbo].[voucher] where voucher_id=%d",vid);
        ResultSet rs2;
        int u_id = 0;
        try {
            rs2 = stmt.executeQuery(query2);
            rs2.next();
            u_id=rs2.getInt(3);
            user_id_label.setText(Integer.toString(u_id));
        } catch (SQLException ex) {
            Logger.getLogger(search_by_voucher_id.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String query3 = String.format("Select * from [voucher].[dbo].[users] where user_id=%d",u_id);
        ResultSet rs3;
        try {
            rs3 = stmt.executeQuery(query3);
            rs3.next();
            String use_name=rs3.getString(2);
            user_name_label.setText(use_name);
        } catch (SQLException ex) {
            Logger.getLogger(search_by_voucher_id.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_search_btnMouseClicked

    private void print_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_btnMouseClicked
        printRecord(panel_to_print);
    }//GEN-LAST:event_print_btnMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        voucher_display cd;
        try {
            cd = new voucher_display(name);
            this.setVisible(false);
                cd.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(search_by_voucher_id.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(search_by_voucher_id.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_by_voucher_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_by_voucher_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_by_voucher_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_by_voucher_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_by_voucher_id().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount_label;
    private javax.swing.JLabel description_label;
    private javax.swing.JLabel expense_sector_id_label;
    private javax.swing.JLabel issue_date_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_to_print;
    private javax.swing.JLabel print_btn;
    private javax.swing.JLabel search_btn;
    private javax.swing.JLabel show_name_Label;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel user_id_label;
    private javax.swing.JLabel user_name_label;
    private javax.swing.JLabel vc_hub_btn;
    private javax.swing.JTextField voucher_id_label;
    // End of variables declaration//GEN-END:variables


   private void printRecord(JPanel panel)
   {
       PrinterJob printerJob = PrinterJob.getPrinterJob();
       printerJob.setJobName("Print Record");
       printerJob.setPrintable(new Printable(){
           @Override
           public int print(Graphics graphics,PageFormat pageFormat,int pageIndex) throws PrinterException{
               if (pageIndex>0)
               {
                   return Printable.NO_SUCH_PAGE;
               }
               Graphics2D graphics2D=(Graphics2D)graphics;
               graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
               graphics2D.scale(0.5, 0.5);
               panel.paint(graphics2D);
               return Printable.PAGE_EXISTS;
           }
       }); 
      boolean returningResult=printerJob.printDialog();
      if (returningResult){
          try{
              printerJob.print();
          }catch(PrinterException printerException){
              
          }
      }
   }


}


