
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class summary extends javax.swing.JFrame {
    int name;
    private  Statement stmt = null;
    private static Connection connection ;
    /**
     * Creates new form summary
     */
    public summary() {
        initComponents();
    }
    
    public summary(int u_nam) throws ClassNotFoundException, SQLException {
        initComponents();
        name=u_nam;
        
        System.out.println("DB connection Starting..");
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost:1433;"
                + "user=sa;password=p@ssword13;" 
                + "databaseName=voucher;";
        connection = DriverManager.getConnection(connectionUrl);
        System.out.println("Connected database successfully.........");
        stmt = connection.createStatement();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        vc_hub_btn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser_from = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser_to = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cost_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        saving_label = new javax.swing.JLabel();
        saving_cost_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 449));
        getContentPane().setLayout(null);

        upperPanel.setBackground(new java.awt.Color(24, 44, 97));
        upperPanel.setLayout(null);

        vc_hub_btn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        vc_hub_btn.setForeground(new java.awt.Color(255, 255, 255));
        vc_hub_btn.setText("Summary of shop");
        upperPanel.add(vc_hub_btn);
        vc_hub_btn.setBounds(31, 31, 320, 38);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go_back_btn.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        upperPanel.add(jLabel10);
        jLabel10.setBounds(480, 20, 100, 50);

        getContentPane().add(upperPanel);
        upperPanel.setBounds(0, 0, 570, 90);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setText("ENTER THE TIME RANGE OF WHICH YOU WANT TO SEE THE SUMMARY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(64, 0, 460, 55);
        jPanel1.add(jDateChooser_from);
        jDateChooser_from.setBounds(54, 103, 157, 36);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculate.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(425, 84, 123, 55);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("From");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(54, 61, 95, 34);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("To");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 70, 80, 20);
        jPanel1.add(jDateChooser_to);
        jDateChooser_to.setBounds(240, 100, 150, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total Savings:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 210, 100, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Total Cost:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 170, 100, 30);

        cost_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cost_label);
        cost_label.setBounds(170, 170, 130, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 170, 120, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(170, 170, 120, 30);

        saving_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(saving_label);
        saving_label.setBounds(170, 214, 110, 30);

        saving_cost_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(saving_cost_label);
        saving_cost_label.setBounds(60, 250, 490, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 96, 570, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        java.util.Date date_from=jDateChooser_from.getDate();
        java.sql.Date sDate_from = new java.sql.Date(date_from.getTime());
        SimpleDateFormat sdf_from = new SimpleDateFormat("DD/MM/YY");
        String from = sdf_from.format(sDate_from);
        
        java.util.Date date_to=jDateChooser_to.getDate();
        java.sql.Date sDate_to = new java.sql.Date(date_to.getTime()); 
        SimpleDateFormat sdf_to = new SimpleDateFormat("DD/MM/YY");
        String to = sdf_to.format(sDate_to);
     
        String query = String.format("Select * from [voucher].[dbo].[voucher_details]");
        int cost=0,savings=0;
        
        
        try {
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                int vouch_id=rs.getInt(1);
                java.sql.Date sDate=rs.getDate(4);
                java.util.Date utilDate = new java.util.Date(sDate.getTime());
                SimpleDateFormat sdf1 = new SimpleDateFormat("DD/MM/YY");
                String issu_date = sdf1.format(utilDate);
   
                if ((issu_date.compareTo(from)>=0 && issu_date.compareTo(to)<=0)&& vouch_id/100==1)
                {
                    cost+=rs.getInt(5);
                }
                else if ((issu_date.compareTo(from)>=0 && issu_date.compareTo(to)<=0)&& vouch_id/100==2)
                {
                    savings+=rs.getInt(5);
                }
            }
            cost_label.setText(Integer.toString(cost));
            saving_label.setText(Integer.toString(savings));
            if (cost>savings)
            {
                saving_cost_label.setText("There is "+Integer.toString(cost-savings)+" taka loss in the given range of time");
            }
            else if(savings>cost)
            {
                saving_cost_label.setText("There is "+Integer.toString(savings-cost)+" taka profit in the given range of time");
            }
            else if(savings==cost) 
            {
                saving_cost_label.setText("There is no profit or loss in the given range of time");
            }
        } catch (SQLException ex) {
            Logger.getLogger(summary.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        voucher_display cd;
        try {
            cd = new voucher_display(name);
            this.setVisible(false);
                cd.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(search_by_voucher_id.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(search_by_voucher_id.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new summary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cost_label;
    private com.toedter.calendar.JDateChooser jDateChooser_from;
    private com.toedter.calendar.JDateChooser jDateChooser_to;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel saving_cost_label;
    private javax.swing.JLabel saving_label;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel vc_hub_btn;
    // End of variables declaration//GEN-END:variables
}
