
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class voucher_display extends javax.swing.JFrame {
    int name;
    private  Statement stmt = null;
    private static Connection connection ;
    /**
     * Creates new form voucher_display
     */
    public voucher_display() {
        initComponents();
         
    }
    public voucher_display(int username ) throws ClassNotFoundException, SQLException {
        initComponents();
        name=username;
        System.out.println("DB connection Starting..");
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost:1433;"
                + "user=sa;password=p@ssword13;" 
                + "databaseName=voucher;";
        connection = DriverManager.getConnection(connectionUrl);
        System.out.println("Connected database successfully.........");
         stmt = connection.createStatement();
        showInfo();
    }
    void showInfo() throws SQLException
    {
        String query1 = String.format("Select * from [voucher].[dbo].[users] where user_id=%d",name);
        ResultSet rs1 = stmt.executeQuery(query1);
        rs1.next();
        String u_name=rs1.getString(2);
        show_name_Label.setText(u_name);
        String query = "Select * from [voucher].[dbo].[voucher_details]";
        try {
            ResultSet rs = stmt.executeQuery(query);
            
           DefaultTableModel model;
           model=(DefaultTableModel) voucher_info_table.getModel();
           model.setRowCount(0);
            
            while(rs.next())
        {
            //System.out.println(rs.getString(1)+rs.getString(2));
            String v_id=rs.getString(1);
            String es_id=rs.getString(2);
            String desp=rs.getString(3);
            
            
            java.sql.Date sDate=rs.getDate(4);
            java.util.Date utilDate = new java.util.Date(sDate.getTime());
            SimpleDateFormat sdf1 = new SimpleDateFormat("MMM dd,yyyy");
            System.out.println(sdf1);
            String DOB_String = sdf1.format(utilDate);
            
            String amn=rs.getString(5);
            
           model.insertRow(model.getRowCount(),new Object[]{v_id,es_id,desp,DOB_String,amn});
        }
        } catch (SQLException ex) {
            Logger.getLogger(voucher_display.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        underPanel = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        vc_hub_btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        show_name_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        voucher_info_table = new javax.swing.JTable();
        createVoucher = new javax.swing.JLabel();
        search_by_voucher_id_btn = new javax.swing.JLabel();
        summary = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        underPanel.setBackground(new java.awt.Color(255, 255, 255));
        underPanel.setLayout(null);

        upperPanel.setBackground(new java.awt.Color(24, 44, 97));
        upperPanel.setLayout(null);

        vc_hub_btn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        vc_hub_btn.setForeground(new java.awt.Color(255, 255, 255));
        vc_hub_btn.setText("Voucher Hub");
        upperPanel.add(vc_hub_btn);
        vc_hub_btn.setBounds(31, 31, 240, 38);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello (5).png"))); // NOI18N
        jLabel1.setText("Hello, ");
        upperPanel.add(jLabel1);
        jLabel1.setBounds(460, 20, 90, 50);

        show_name_Label.setBackground(new java.awt.Color(255, 255, 255));
        show_name_Label.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        show_name_Label.setForeground(new java.awt.Color(255, 255, 255));
        upperPanel.add(show_name_Label);
        show_name_Label.setBounds(550, 20, 190, 50);

        underPanel.add(upperPanel);
        upperPanel.setBounds(0, -1, 760, 90);

        voucher_info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voucher ID", "Expense Sector ID", "Description", "Issue Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(voucher_info_table);

        underPanel.add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 710, 190);

        createVoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button.png"))); // NOI18N
        createVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createVoucherMouseClicked(evt);
            }
        });
        underPanel.add(createVoucher);
        createVoucher.setBounds(20, 340, 220, 60);

        search_by_voucher_id_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_by_voucher_id.png"))); // NOI18N
        search_by_voucher_id_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_by_voucher_id_btnMouseClicked(evt);
            }
        });
        underPanel.add(search_by_voucher_id_btn);
        search_by_voucher_id_btn.setBounds(270, 350, 220, 40);

        summary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/summary_btn.png"))); // NOI18N
        summary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                summaryMouseClicked(evt);
            }
        });
        underPanel.add(summary);
        summary.setBounds(510, 340, 180, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoutbtn.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        underPanel.add(jLabel2);
        jLabel2.setBounds(610, 390, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(underPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(underPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createVoucherMouseClicked
        create_Voucher cv;
        try {
            cv = new create_Voucher(name);
            this.setVisible(false);
            cv.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(voucher_display.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(voucher_display.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_createVoucherMouseClicked

    private void search_by_voucher_id_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_by_voucher_id_btnMouseClicked
        search_by_voucher_id sbv;
        try {
            sbv = new search_by_voucher_id(name);
            this.setVisible(false);
            sbv.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(voucher_display.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(voucher_display.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
    }//GEN-LAST:event_search_by_voucher_id_btnMouseClicked

    private void summaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_summaryMouseClicked
          summary sum;
        try {
            sum = new summary(name);
            this.setVisible(false);
            sum.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(voucher_display.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(voucher_display.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_summaryMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        LogIn cd;
        try {
            cd = new LogIn();
            this.setVisible(false);
            cd.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(voucher_display.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(voucher_display.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(voucher_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(voucher_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(voucher_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(voucher_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new voucher_display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createVoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel search_by_voucher_id_btn;
    private javax.swing.JLabel show_name_Label;
    private javax.swing.JLabel summary;
    private javax.swing.JPanel underPanel;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel vc_hub_btn;
    private javax.swing.JTable voucher_info_table;
    // End of variables declaration//GEN-END:variables
}
